<?php
// module/Galerie/view/galerie/galerie/index.phtml:

$title = 'Galerie';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('galerie', ['action' => 'add']) ?>">Add new galerie</a>
	<a href="www.zf-tutorial.localhost/galerie"><img src="<?= $this->basePath('img/photo/carphoto.jpeg') ?>" alt="favicon.ico" px="10" width="100" height="100"></a>
	<a href="www.zf-tutorial.localhost/galerie"><img src="<?= $this->basePath('img/photo/images1.png') ?>" alt
	="favicon.ico" px="10" width="100" height="100"></a>
	<a href="www.zf-tutorial.localhost/galerie"><img src="<?= $this->basePath('img/photo/images2.png') ?>" alt
	="favicon.ico" px="10" width="100" height="100"></a>
	<a href="www.zf-tutorial.localhost/galerie"><img src="<?= $this->basePath('img/photo/images3.png') ?>" alt
	="favicon.ico" px="10" width="100" height="100"></a>
</p>


<?php

$lokal = $this->url(null, array(), true);
#var_dump($lokal);
$bla =  substr($lokal,1,2) . "_" . strtoupper(substr($lokal,1,2));


?>
<p><?= $this->translate('An error occurred','default',$bla) ?></p>
<p><?= $this->translate('Hello','default',$bla) ?></p>


<table class="table">
<tr>
    <th>Autor</th>
    <th>Titel</th>
    <th>Land</th>	
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $galerie) : // <-- change here! ?>
    <tr>
        <td><?= $this->escapeHtml($galerie->autor) ?></td>
        <td><?= $this->escapeHtml($galerie->title) ?></td>
        <td><?= $this->escapeHtml($galerie->land) ?></td>
        <td>
            <a href="<?= $this->url('galerie', ['action' => 'edit', 'id' => $galerie->id]) ?>">Edit</a>
            <a href="<?= $this->url('galerie', ['action' => 'delete', 'id' => $galerie->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
<?php #var_dump($_SESSION); ?>
</table>
<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'galerie']
) ?>