<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Ricardo Sousa')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                     <img src="<?= $this->basePath('img/backend_photo.svg') ?>" height="28" alt="Zend Framework"<?= \Application\Module::VERSION ?>"/>&nbsp;Ricardo Sousa
                    </a>
                </div>
                <div class="collapse navbar-collapse">
				<?= $this->navigation('navigation')
        ->menu()
        ->setMinDepth(0)
        ->setMaxDepth(0)
        ->setUlClass('nav navbar-nav') ?>
				
				 <!--?= $this->navigation('navigation')->menu() ?>-->
                    
                </div>
            </div>
        </nav>
        <div class="container">
		   <?= $this->navigation('navigation')
            ->breadcrumbs()
            ->setMinDepth(0)
            ->setPartial('partial/breadcrumb') ?>
			
			<?php //Locale sprache script
			$_SESSION["item"] = '';
			if (!empty($_GET["locale"])) {
				$_SESSION["locale"] = $_GET["locale"];
			}
			?>
			<ul>
			<li><input type="button" name="de_De" value="Deutsch" style="float: right;"></li>
			<li><input type="button" name="en_En" value="English" style="float: right;"></li>
			<li><input type="button" name="pt_Pt" value="Portuguese" style="float: right;"></li>
			</ul>
			<?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2018 - <?= date('Y') ?> by Ricardo Sousa Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
