<?php
// module/Book/view/book/book/add.phtml:

$title = 'Add new book';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?php
// This provides a default CSS class and placeholder text for the title element:
$book = $form->get('title');
$book->setAttribute('class', 'form-control');
$book->setAttribute('placeholder', 'Book title');


// This provides a default CSS class and placeholder text for the title element:
$land = $form->get('land');
$land->setAttribute('class', 'form-control');
$land->setAttribute('placeholder', 'Land title');


// This provides a default CSS class and placeholder text for the autor element:
$autor = $form->get('autor');
$autor->setAttribute('class', 'form-control');
$autor->setAttribute('placeholder', 'Autor');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');


?>

<?php
$form->setAttribute('action', $this->url('book', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($book) ?>
    <?= $this->formElement($book) ?>
    <?= $this->formElementErrors()->render($book, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($autor) ?>
    <?= $this->formElement($autor) ?>
    <?= $this->formElementErrors()->render($autor, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($land) ?>
    <?= $this->formElement($land) ?>
    <?= $this->formElementErrors()->render($land, ['class' => 'help-block']) ?>
</div>

<?php

echo $this->formHidden($form->get('id'));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();