<?php
// module/Book/view/book/book/index.phtml:

$title = 'My Books';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('book', ['action' => 'add']) ?>">Add new book</a>
</p>

<table class="table">
<tr>
    <th>Autor</th>
    <th>Title</th>
	<th>Land</th>

	
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $book) : // <-- change here! ?>
    <tr>
        <td><?= $this->escapeHtml($book->autor) ?></td>
        <td><?= $this->escapeHtml($book->title) ?></td>
		<td><?= $this->escapeHtml($book->land) ?></td>
        <td>
            <a href="<?= $this->url('book', ['action' => 'edit', 'id' => $book->id]) ?>">Edit</a>
            <a href="<?= $this->url('book', ['action' => 'delete', 'id' => $book->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>




</table>
<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'book']
) ?>


