<div class="jumbotron">


	


    <h1 align="center">Acess Granted, Congratulations!</h1>

    

   
	<p><?= $this->translate(''); ?></p>
	<p><?= $this->translate("Translation from german Hello World", "default", "de_De"); ?></p>
	<p><?= $this->translate("Translation form spanish", "default", "es_Es"); ?></p>
	<?php $locale = "de_De"; ?>
	
	<p><?= $this->translate("Hello world", "default", "$locale"); ?></p>
	
	
	
	<p><a class="btn btn-success pull-right " href="http://zf-tutorial.localhost/ola" target="_blank">Documentation</a></p>

	
	
	
	
	
	
	
	
</div>